### ISSUE TITLE
Could you pass the message?

### ISSUE THREAD

**Issue by Jan-Blasiak** [Maleclypse/cataclysmdda-0.D-Windows-Tiles-9638-saltworks#1]
Hey M

I got myself blocked on the CDDA github for jokingly calling someone a glue eater, due to the fact that github has no social features whatsoever this is the only way I can currently see of contacting people about it, I would like to say that I read the CoC and shall refrain from doing so from now on, and I've found some more issues I'd like to report in a more civilized manner.

I would appreciate if you could pass the message to someone who has blocking permissions.

**Comment by Maleclypse** [comment]
Hey Jan, I've passed it on into the internal moderation channel the team has.  It may take a day or two for someone to see it and make a decision, I don't know for sure.  But I'll let you know once I have received an answer back.

**Comment by Jan-Blasiak** [comment]
Thanks

**Comment by Maleclypse** [comment]
Appeal granted.  You should have access again soon.  If a day or so goes by and you don't please let me know.  I'll close this in a couple days if I don't hear from you.

**Comment by Jan-Blasiak** [comment]
Thanks, everything works already, I even managed to post the issue I wanted already, thanks for the help.
